server:
  port: 9090


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost


spring:
  cloud:


    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: ms-alumno-service
          uri: lb://ms-alumno-service
          predicates:
            - Path=/alumno/**
        - id: ms-profesores-service
          uri: lb://ms-profesores-service
          predicates:
            - Path=/profesores/**
        - id: ms-curso-service
          uri: lb://ms-curso-service
          predicates:
            - Path=/curso/**







